import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar />
      <Head>
        <title>Responsive Navbar</title>
        <meta name="description" content="Generated by cliqonrefraich" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}
